[global]
# If True, will show a warning when you run a Streamlit-enabled script via "python my_script.py".
# Default: true
showWarningOnDirectExecution = false

[theme]
primaryColor="#39a9db"
backgroundColor="#003049"
secondaryBackgroundColor="#31333F"
textColor="#ffffea"
font="sans serif"

[server]
runOnSave = true

# port = 80
# baseUrlPath = ""
# enableCORS = false
# enableXsrfProtection = false
# enableWebsocketCompression = false
